#!/bin/bash
echo "Save As:"
read varsave
echo \

echo "Pool URL:"
read varlink
echo \

echo "Pool Worker:"
read varworker
echo \

echo "Worker Password:"
read varpass
echo \

echo "Miner Frequency"
echo "Can be 100, 125, 150, 175, 200"
echo "Use cooling for anything passed 100"
read varfreq

> $varsave

echo "#!/bin/bash" >> $varsave
echo "cd cgminer" >> $varsave
echo "sudo ./cgminer -o $varlink -u $varworker -p $varpass --suggest-diff 32 --gekko-newpac-freq $varfreq" >> $varsave

chmod +x $varsave
